version: '3.9'

services:
  carrentalapp:
    container_name: carrentalapp
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DB_URL: ${DB_URL}
        PG_USER: ${PG_USER}
        PG_PASSWORD: ${PG_PASSWORD}
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://carrentaldb:5432/postgres
      PG_USER: postgres
      PG_PASSWORD: postgres
    depends_on:
      - carrentaldb
  carrentaldb:
    container_name: carrentaldb
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
